-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 10:44:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kita
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kita` ;

-- -----------------------------------------------------
-- Schema kita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kita` DEFAULT CHARACTER SET utf8 ;
USE `kita` ;

-- -----------------------------------------------------
-- Table `kita`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`grupos` (
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `kita`.`grupos` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `kita`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`roles` (
  `id` INT NOT NULL,
  `rol` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `kita`.`roles` (`id` ASC);


-- -----------------------------------------------------
-- Table `kita`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`usuarios` (
  `usuarios_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `id_rol_usu` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `id_rol_usu`),
  CONSTRAINT `id_rol_usu`
    FOREIGN KEY (`id_rol_usu`)
    REFERENCES `kita`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `usuarios_id_UNIQUE` ON `kita`.`usuarios` (`usuarios_id` ASC);

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `kita`.`usuarios` (`nombre` ASC);

CREATE INDEX `id_rol_usu_idx` ON `kita`.`usuarios` (`id_rol_usu` ASC);


-- -----------------------------------------------------
-- Table `kita`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`profesores` (
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_nac` DATE NULL,
  `nombre_grupo` VARCHAR(15) NOT NULL,
  `usuarios_id_prof` INT NOT NULL,
  PRIMARY KEY (`dni`, `nombre_grupo`, `usuarios_id_prof`),
  CONSTRAINT `nombre_grupo_prof`
    FOREIGN KEY (`nombre_grupo`)
    REFERENCES `kita`.`grupos` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usuarios_id_prof`
    FOREIGN KEY (`usuarios_id_prof`)
    REFERENCES `kita`.`usuarios` (`usuarios_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `kita`.`profesores` (`dni` ASC);

CREATE INDEX `nombre_grupo_UNIQUE` ON `kita`.`profesores` (`nombre_grupo` ASC);

CREATE INDEX `usuarios_id_prof_idx` ON `kita`.`profesores` (`usuarios_id_prof` ASC);


-- -----------------------------------------------------
-- Table `kita`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`alumnos` (
  `alumno_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `alergias` TEXT NULL,
  `observaciones` TEXT NULL,
  `auto_salidas` TINYINT NOT NULL DEFAULT 0,
  `auto_fotos` TINYINT NOT NULL DEFAULT 0,
  `fecha_nac` DATE NOT NULL,
  `nombre_grupo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`alumno_id`, `nombre_grupo`),
  CONSTRAINT `nombre_grupo_alum`
    FOREIGN KEY (`nombre_grupo`)
    REFERENCES `kita`.`grupos` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `alumno_id_UNIQUE` ON `kita`.`alumnos` (`alumno_id` ASC);

CREATE UNIQUE INDEX `nombre_grupo_UNIQUE` ON `kita`.`alumnos` (`nombre_grupo` ASC);


-- -----------------------------------------------------
-- Table `kita`.`informacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`informacion` (
  `informacion_id` INT NOT NULL AUTO_INCREMENT,
  `informacion` TEXT NOT NULL,
  `nombre_grupo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`informacion_id`, `nombre_grupo`),
  CONSTRAINT `nombre_grupo_info`
    FOREIGN KEY (`nombre_grupo`)
    REFERENCES `kita`.`grupos` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `informacion_id_UNIQUE` ON `kita`.`informacion` (`informacion_id` ASC);


-- -----------------------------------------------------
-- Table `kita`.`padres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`padres` (
  `padres_id` INT NOT NULL AUTO_INCREMENT,
  `nombre1` VARCHAR(45) NULL,
  `telefono1` INT NULL,
  `email1` VARCHAR(30) NULL,
  `nombre2` VARCHAR(45) NULL,
  `telefono2` INT NULL,
  `email2` VARCHAR(30) NULL,
  `alumno_id` INT NOT NULL,
  `usuarios_id_pad` INT NOT NULL,
  PRIMARY KEY (`padres_id`, `alumno_id`, `usuarios_id_pad`),
  CONSTRAINT `alumno_id`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `kita`.`alumnos` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `usuarios_id_pad`
    FOREIGN KEY (`usuarios_id_pad`)
    REFERENCES `kita`.`usuarios` (`usuarios_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `alumno_id_UNIQUE` ON `kita`.`padres` (`alumno_id` ASC);

CREATE INDEX `usuarios_id_pad_idx` ON `kita`.`padres` (`usuarios_id_pad` ASC);


-- -----------------------------------------------------
-- Table `kita`.`informes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`informes` (
  `alumno_id` INT NOT NULL,
  `deposicion` TINYINT NOT NULL DEFAULT 0,
  `suenio` INT NULL,
  `comida` TINYINT NOT NULL DEFAULT 0,
  `bebida` TINYINT NOT NULL DEFAULT 0,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`alumno_id`),
  CONSTRAINT `alumno_id_inf`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `kita`.`alumnos` (`alumno_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `alumno_id_UNIQUE` ON `kita`.`informes` (`alumno_id` ASC);

CREATE UNIQUE INDEX `fecha_UNIQUE` ON `kita`.`informes` (`fecha` ASC);


-- -----------------------------------------------------
-- Table `kita`.`calendario`
-- -----------------------------------------------------
CREATE TABLE `calendario` (
  `dia` date NOT NULL,
  `evento` varchar(45) NOT NULL,
  `calendario_id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`calendario_id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX `dia_id_UNIQUE` ON `kita`.`calendario` (`dia_id` ASC);


-- -----------------------------------------------------
-- Table `kita`.`comedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kita`.`comedor` (
  `menu_id` INT NOT NULL AUTO_INCREMENT,
  `dia_id` DATE NOT NULL,
  `snack` VARCHAR(45) NULL,
  `desayuno` VARCHAR(45) NULL,
  `plato_principal` VARCHAR(45) NULL,
  `postre` VARCHAR(45) NULL,
  `nombre_grupo` VARCHAR(15) NOT NULL,
  `comedorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`menu_id`, `dia_id`, `nombre_grupo`),
  CONSTRAINT `dia_id`
    FOREIGN KEY (`dia_id`)
    REFERENCES `kita`.`calendario` (`dia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nombre_grupo_com`
    FOREIGN KEY (`nombre_grupo`)
    REFERENCES `kita`.`grupos` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `menu_id_UNIQUE` ON `kita`.`comedor` (`menu_id` ASC);

CREATE UNIQUE INDEX `dia_id_UNIQUE` ON `kita`.`comedor` (`dia_id` ASC);

CREATE INDEX `nombre_grupo_idx` ON `kita`.`comedor` (`nombre_grupo` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
